apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: custom-web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: custom-web-content
        configMap:
          name: custom-nginx-index
